version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./app/.env.example:/app/.env
    depends_on:
      - db
    command: bash -c 'sleep 3 && npm test'
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
