version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./app/.env.example:/app/.env
  caddy:
    build:
      context: .
      dockerfile: services/caddy/Dockerfile
    volumes:
      - .:/app
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
