---

- hosts: all
  gather_facts: no
  tasks:

    - community.docker.docker_network:
        name: devops-example

    - community.docker.docker_container:
        name: app
        # Обязатлеьно указываем тег, который хотим деплоить
        # Если образа на сервере нет, Ansible его автоматически скачает
        image: "koshkarik/hexlet-test-deploy:{{ version }}"
        # Подключаем супервизор
        # Если контейнер остановится, например, из-за ошибок
        # супервизор докера его перезапустить
        restart_policy: always
        # Запускаем если не запущен
        state: started
        networks:
          - name: devops-example
        # Делаем доступным снаружи
        ports:
          - 8080:8080 
        env: # Настраиваем
          NODE_ENV: production
          DATABASE_NAME: postgres
          DATABASE_USERNAME: doadmin
          DATABASE_PASSWORD: AVNS_wWU2usRBxpPgldJIYwi
          DATABASE_PORT: 25060
          DATABASE_HOST: db-postgresql-fra1-48994-do-user-11933137-0.b.db.ondigitalocean.com

